### ISSUE TITLE
Remove main.cpp

### ISSUE THREAD

**Issue by Abrynos** [maxortner01/ck2-Save-Parser#1]
Many C++ projects use `make` as a build-tool and automatically compile ALL .cpp files found. In addition to that it's considered standard to add libraries (such as this one) as a [submodule ](https://git-scm.com/book/en/v2/Git-Tools-Submodules) in git. Having a file that contains a `main` method in such submodule would then break the automatic compiling process as that file has to be excluded manually. 

I'd like to request removing the file and adding a markdown file with the example usage instead (maybe in README.md)

**Comment by maxortner01** [comment]
Ok, I see
